### ISSUE TITLE
Axios error 404

### ISSUE THREAD

**Issue by legendary0001** [Blad3Mak3r/RedditMemes#124]
Whenever there is allowNSFW: false in code i receive error 
`Request failed with status code 404
     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)`

**Comment by Blad3Mak3r** [comment]
@legendary0001  can u add to the issue the code used on the request, actually on the tests all works correctly.

https://github.com/Blad3Mak3r/RedditMemes/blob/master/src/__tests__/api.test.ts#L8-L10

**Comment by legendary0001** [comment]
@Blad3Mak3r my code was getRandomMeme( { allowNSFW: false })
And their no example of that either

**Comment by Blad3Mak3r** [comment]
When you use the ``allowNSFW`` filter with JavaScript (instead of TypeScrript), have to set a reddit, or just use ``undefined`` keyword, This happens because javascript does not show typing errors, which if it would be shown in typescript.

```javascript
getRandomMeme(undefined, { allowNSFW: false })
```

Perharps in the next version we will make this clearer and no need to use undefined.

**Comment by legendary0001** [comment]
Thanks
